In [1]:
import numpy

N, M = map(int, input().split())

arr1 = numpy.array([list(map(int, input().split())) for n in range(N)])
arr2 = numpy.array([list(map(int, input().split())) for n in range(N)])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 // arr2)
print(arr1 % arr2)
print(arr1 ** arr2)



1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]
